export const routes = {
  HEADER: "/",
  SIGNIN: "/signin",
  SIGNUP: "/signup",
  HOME: "/home",
  FAVORITE: "/favoris",
  HISTORY: "/history",
  CATEGORIES: "/categories",
  MODERATORS: "/moderateurs",
  MODERATOREDIT: "/editmoderateur",
  ADDMODERATOR: "/addmoderateur",
  PASSWORDEDIT: "/editpassword",
  EDITARTICLE: "/editarticle",
  SETTINGS: "/settings",
  ARTICLE: "/article",
  PROFILE: "/profile",
  PROFILEEDIT: "/editprofile",
};
