version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # Disable X-Pack security
    ports:
      - "9200:9200"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
 
  client:
    build:
      context: ./client
      dockerfile: Dockerfile 
    ports:
      - "5173:5173"
    depends_on:
      - elasticsearch
    volumes:
      - ./client/src:/app/src

# networks:
#   default:
#     external:
#       name: _sciverse

